### ISSUE TITLE
更新过程发生错误bug

### ISSUE THREAD

**Issue by Jzhnakui** [HammerPDF/Scholar-PDF-Reader#11]
# 现象
点击检查更新后:
![image](https://user-images.githubusercontent.com/49728819/137574788-9d95756e-91a1-4622-95c9-0c1c2076177e.png)

下载更新开始时出现错误, 截图如下:
![image](https://user-images.githubusercontent.com/49728819/137574723-b8c442e9-58bd-4b8d-ab39-fdaa4a7a2a36.png)

跟新下载中出现错误如下:
![image](https://user-images.githubusercontent.com/49728819/137574743-593a903a-4aa2-4926-b526-ad3eead9184c.png)

# win版本
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2021/‎8/‎21
操作系统内部版本	19042.1288
体验	Windows Feature Experience Pack 120.2212.3920.0

**Comment by wongself** [comment]
请保证网络连接是否顺畅，能否正常连接至 Github。您目前所使用的版本为 [v1.0.0](https://github.com/HammerPDF/Smart-Scientific-Reader/releases/tag/v1.0.0)，建议您手动更新至最新版本 [v1.0.1](https://github.com/HammerPDF/Smart-Scientific-Reader/releases/tag/v1.0.1)。
