### ISSUE TITLE
无法打开“Hammer PDF”，因为无法验证开发者。

### ISSUE THREAD

**Issue by mwzking** [HammerPDF/Scholar-PDF-Reader#12]
苹果m1芯片，安装报错
![image](https://user-images.githubusercontent.com/62544410/137574986-45cb59fa-2033-4f1a-bf45-0a753214a47c.png)

**Comment by wongself** [comment]
对于 macOS，因无法验证开发者而无法打开应用时，只需允许`安全性与隐私`中的`仍要打开`选项即可。
详见[发布说明](https://github.com/HammerPDF/Smart-Scientific-Reader/releases/tag/v1.0.1)。

**Comment by wongself** [comment]
我们将更新下载页的说明，以告知 macOS 用户这项使用要求。
