### ISSUE TITLE
出现错误 Grobid抽取PDF文档失败

### ISSUE THREAD

**Issue by Quantum-Electrodynamics** [HammerPDF/Scholar-PDF-Reader#14]
我不知道发生了什么
![image](https://user-images.githubusercontent.com/44795304/137577295-dad65c5e-2228-434e-a617-9214955cde00.png)

**Comment by wongself** [comment]
请问这是哪一篇 PDF 文档？

**Comment by Quantum-Electrodynamics** [comment]
> 请问这是哪一篇 PDF 文档？

声乐发声的频谱分析研究_徐琳，从知网下下来的

**Comment by wongself** [comment]
我们已经定位到这一错误，将在下一版本中修复。
