### ISSUE TITLE
关于翻译的意见

### ISSUE THREAD

**Issue by usethisforlearn** [HammerPDF/Scholar-PDF-Reader#15]
在查看论文时，不希望总是跟着翻译全程手打，但选取英文翻译的中文过程中时，会直接关闭翻译界面，希望能改进一下，能支持选取翻译出来的中文

**Comment by wongself** [comment]
目前点击翻译面板后面板就会消失，这是一个程序错误。我们将在下个版本更新中修复它。

**Comment by SGS4ever** [comment]
目前网页端的翻译面板是固定在屏幕下方吧？希望可以把翻译面板独立出来，允许用户拖动位置，或者直接加到右边栏，成为右边栏的一个功能模块。

**Comment by wongself** [comment]
> 目前网页端的翻译面板是固定在屏幕下方吧？希望可以把翻译面板独立出来，允许用户拖动位置，或者直接加到右边栏，成为右边栏的一个功能模块。

我们会尝试将翻译面板变成页面内可拖动的形式。
