### ISSUE TITLE
关于对Archlinux/Manjaro的支持

### ISSUE THREAD

**Issue by fightingxiaoxiao** [HammerPDF/Scholar-PDF-Reader#16]
开发者您好，我的操作系统是Manjaro，这一类的Linux发行版一般通过AUR安装第三方包。我根据release中提供的.deb文件在AUR上上传了[hammer-pdf](https://aur.archlinux.org/packages/hammer-pdf/)这个包，目前软件能够开启但但存在功能性问题。

![Screenshot_20211017_113827](https://user-images.githubusercontent.com/32048133/137609984-1b7c26ef-c7a6-49bb-bb39-294a4af1db1d.png)

此外我不了解相关的行为是否不当，如您需要包的维护权，可以联系我。

**Comment by fightingxiaoxiao** [comment]
目前存在的一个问题是部分PDF文档标识和选取错位
![Screenshot_20211017_1](https://user-images.githubusercontent.com/32048133/137610470-8dca2e4b-f61d-4f3f-b8e6-3968c37dcb87.png)

系统简要信息
Linux Kernel：5.14.10-1
OS：Manjaro 21.1.5 Pahvo
桌面：KDE 5.86.0 / Plasma 5.22.5(基于X11)
分辨率：3840*2160
DPI缩放：250%

**Comment by wongself** [comment]
请问这是哪一篇文档，从哪个网站下载，是Elsevier么？

**Comment by wongself** [comment]
我们团队对于 Linux 各类发行版的特性的了解还不充足。后续我们会将安装包同步上传至 ArchLinux，届时我们会通知您。当我们准备完毕并告知您后，希望您能删除您个人上传的安装包，以免产生不必要的误会。

**Comment by fightingxiaoxiao** [comment]
> 请问这是哪一篇文档，从哪个网站下载，是Elsevier么？



> 请问这是哪一篇文档，从哪个网站下载，是Elsevier么？

**Comment by fightingxiaoxiao** [comment]
> 请问这是哪一篇文档，从哪个网站下载，是Elsevier么？

是从Elsevier上下载的， DOI号是10.1016/j.coldregions.2021.103347。另外我试了下，在windows10下也存在同样的问题。其他文献暂时没有发现问题。

**Comment by fightingxiaoxiao** [comment]
> 我们团队对于 Linux 各类发行版的特性的了解还不充足。后续我们会将安装包同步上传至 ArchLinux，届时我们会通知您。当我们准备完毕并告知您后，希望您能删除您个人上传的安装包，以免产生不必要的误会。

感谢你们的努力，届时您可以通过我的主页的邮箱联系我。

**Comment by wongself** [comment]
> 是从Elsevier上下载的， DOI号是10.1016/j.coldregions.2021.103347。另外我试了下，在windows10下也存在同样的问题。其他文献暂时没有发现问题。

我们此前发现来自 Elsevier 的论文通过 PDF.js 进行渲染时会出现文字层错位的错误，这并非在我们的预期内，我们会尝试修复该问题，并持续关注 PDF.js 的更新动态。

**Comment by wongself** [comment]
在 v1.2.2 更新中，我们升级了 PDF.js 以改善文字层的渲染效果。另外，我们还为 Linux 用户提供 AppImage 格式的安装包，能满足大多数 Linux 发行版的使用需求。
