### ISSUE TITLE
文件大小过于受限

### ISSUE THREAD

**Issue by LexTran** [HammerPDF/Scholar-PDF-Reader#17]
试用了一下，感觉很不错，界面也很简洁，不过仅支持20M以内的文件大小使用起来有点受限，学术不仅是阅读论文，还需要阅读很多专著吧，建议改进一下

**Comment by wongself** [comment]
最适合使用 Hammer PDF 进行阅读的 PDF 文档类型是**计算机科学领域的单篇学术论文**。
当初设置 20MB 上传大小限制的考量是，Hammer PDF 会对上传的文档进行文本结构抽取和学术信息抽取，这一过程所耗费的时间会随着文本量的扩充而显著增加。
鉴于确有用户需要阅读大小超过 20MB 的 PDF 文档，我们后续将完全去除桌面端的文件大小限制，但默认不会为其进行学术信息抽取。

**Comment by LexTran** [comment]
好的好的，感谢答复，期待新版本！
建议可以考虑将学术信息抽取和文本结构抽取功能设为可选项，在使用引导中进行说明，用户可以自由根据需要自行选择是否开启该功能

**Comment by wongself** [comment]
感谢反馈，我们将在下一版本的更新中增加这一功能。
