### ISSUE TITLE
获取论文实体信息失败

### ISSUE THREAD

**Issue by loukai99** [HammerPDF/Scholar-PDF-Reader#18]
![image](https://user-images.githubusercontent.com/48688304/137616320-6cfb424a-462e-4cb3-8af6-860c5b343558.png)
挺正常的一篇论文，16年谷歌deepmind团队发表的Matching Networks for One Shot Learning，报错获取论文实体信息失败。

**Comment by wongself** [comment]
经过初步检查，我们发现文档结构化模型将该论文的附录部分识别为`body`，致使信息抽取模型处理了大量无效信息，因而产品无法正确获取实体信息。
我们将在本周的版本更新中修复这一错误，感谢反馈！
