### ISSUE TITLE
文档打开无法显示汉字

### ISSUE THREAD

**Issue by zihluwang** [HammerPDF/Scholar-PDF-Reader#19]
这是使用HammerPDF打开的效果：![image](https://user-images.githubusercontent.com/47817169/137621409-d8d4b685-e000-4634-affa-1ef9db2bc2fe.png)
这是使用浏览器打开的效果：
![image](https://user-images.githubusercontent.com/47817169/137621447-7fe5db1f-7c4e-4deb-be24-91f0945dd6f6.png)

DOI：10.13487/j.cnki.imce.019229

**Comment by wongself** [comment]
经过初步检查，我们发现我们没有正确调用 PDF.js 的中文字符集。感谢反馈，这一错误将在下一版本中修复。
