### ISSUE TITLE
使用体验反馈

### ISSUE THREAD

**Issue by alcalaL22** [HammerPDF/Scholar-PDF-Reader#21]
![image](https://user-images.githubusercontent.com/92688227/137638887-1a6d136c-21e6-470e-b605-3f3dbf4faab5.png)
不能正常跳转

![image](https://user-images.githubusercontent.com/92688227/137638963-81d4e9c3-a262-4ac6-b25f-ae8de4339e59.png)
定位紫色但是在pdf中全是蓝色，不能很好区分，同时定位点击返回后，直接返回到开始的位置。

**Comment by wongself** [comment]
我们将在下一版本更新中修改各类术语的显示配色，以提升辨认度。
关于条目跳转的问题，我们还在尝试其他展示方式，可能无法赶上下次更新。
感谢您的反馈！
