### ISSUE TITLE
windows客户端翻译失效

### ISSUE THREAD

**Issue by QbzQbz** [HammerPDF/Scholar-PDF-Reader#22]
![image](https://user-images.githubusercontent.com/35763844/137836718-bc8154bc-9482-44f8-9f16-adbcc7f15db5.png)
如图，windows客户端经常遇到翻译失效问题，选中后显示暂无翻译，但与此同时网页端翻译功能正常。

**Comment by wongself** [comment]
Hammer PDF 目前使用的是百度翻译标准版接口，其每秒最大吞吐量为1。
另外，我们团队无法复现该问题，请检查您的网络情况。
