### ISSUE TITLE
划词、编辑、结构化、问答

### ISSUE THREAD

**Issue by Elinpf** [HammerPDF/Scholar-PDF-Reader#23]
1. PDF文档划词选择体验不好，在边缘选择的时候经常变成了全选。
2. 好像还没有编辑功能，目前只能是浏览。
3. 特性提到的结构化，并没有得到体现。看起来只是将特性单词划出来了而已。并不是将重点勾画出来。或者是将文档解构。
4. 问答里面好像只能是查询会议什么的，对于专业名词的解释并不能识别。

还有挺多地方需要持续迭代的，会持续关注。

**Comment by wongself** [comment]
1. 划词体验将在下个版本更新中改善。
2. 暂时无法编辑 PDF 文档，但我们正在进行标注笔记功能的开发。
3. 获取术语等名词需要结构化 PDF 文档，将其分为段落并送入学术模型获取关键信息。今后我们将尝试推出阅读模式，带来更好的阅读体验。
4. 问答的主要功能已经在相关界面写明，暂不支持会议推荐、学术搜索等以外的功能。

**Comment by zjhellofss** [comment]
@wongself 
贵司的pdf阅读器总体来说比较好用，但是作为一个pdf阅读器最好有高亮、下划线以及添加批注的功能。

**Comment by BITLiuSH** [comment]
@zjhellofss 
非常感谢您的反馈。
高亮、下划线以及批注等笔记功能正在开发中，将在后续一到两个版本中发布。敬请期待。

**Comment by LGAG** [comment]
希望可以增加ctrl + tab快捷键切换操作

**Comment by wongself** [comment]
> 希望可以增加ctrl + tab快捷键切换操作

目前，你可以在软件内使用`Ctrl+Num`组合键快速切换标签页，使用`Ctrl+W`组合键关闭标签页。
