### ISSUE TITLE
内容错位bug

### ISSUE THREAD

**Issue by yangquan0310** [HammerPDF/Scholar-PDF-Reader#24]
### 内容错位
![capture_20211015130550370](https://user-images.githubusercontent.com/51433113/137915291-52301322-4e0a-442d-a870-48642ca4f4c7.jpg)

**Comment by BITLiuSH** [comment]
请问这是哪一篇 PDF 文档？

**Comment by JUNXYU** [comment]
同样碰到这个问题，几乎每一篇文献在选中文字时都会出现重影

**Comment by wongself** [comment]
我们正在尝试将 PDF.js (Mozilla) 更换为显示效果更佳的 PDF.js Express (PDFTron)，后者本月上旬刚刚发布。
这一过程耗时略长，预计本周周五前发布。
