### ISSUE TITLE
一直提示Grobid不可用

### ISSUE THREAD

**Issue by TingxunShi** [HammerPDF/Scholar-PDF-Reader#25]
![image](https://user-images.githubusercontent.com/29669156/138128300-3572a472-4343-4168-a3cf-fa15a8a8426e.png)

Windows桌面版1.0.1

**Comment by wongself** [comment]
很抱歉，刚才我们后台的学术服务无征兆地断线了，现已重新启动。

**Comment by TingxunShi** [comment]
感谢解答，很及时！
