### ISSUE TITLE
对esc键有莫名其妙的占用情况

### ISSUE THREAD

**Issue by CsyBarry** [HammerPDF/Scholar-PDF-Reader#26]
程序启动时对Esc键有莫名其妙的占用，包括无法关闭开始菜单，无法退出截屏，无法关闭Listary的搜索框，若正在进行中文输入，无法关闭候选词框，但依旧可以Ctrl+Esc打开开始菜单，Ctrl+Shift+Esc打开任务管理器，在其他诸如游戏等部分场景并没有出现占用情况

**Comment by wongself** [comment]
问题[已重复](https://github.com/HammerPDF/Smart-Scientific-Reader/issues/9)，将在下一版本中修复。
