### ISSUE TITLE
与ESC键冲突

### ISSUE THREAD

**Issue by pangzi9** [HammerPDF/Scholar-PDF-Reader#29]
window 10 教育版 版本号1809
当前最新win版软件，打开后，全局ESC键失效。无法通过ESC关闭开始菜单，聊天窗口等。

**Comment by wongself** [comment]
问题[已重复](https://github.com/HammerPDF/Smart-Scientific-Reader/issues/9)，将在下一版本中修复，很抱歉给您带来不便。目前我们正在迁移渲染接口，并部署笔记功能，这需要一些时间去完成。
