### ISSUE TITLE
如何获取 Linux 版本？

### ISSUE THREAD

**Issue by glatavento** [HammerPDF/Scholar-PDF-Reader#3]

**Comment by wongself** [comment]
本周晚些时间我们将发布 Linux 版的 Hammer PDF，安装包格式为`deb`。

**Comment by glatavento** [comment]
谢谢

**Comment by wongself** [comment]
Linux 版 Hammer PDF 已发布，详见[此处](https://github.com/HammerPDF/Smart-Scientific-Reader/releases/tag/v1.0.1)。
