### ISSUE TITLE
新版本显示grobid 不可用

### ISSUE THREAD

**Issue by LumosLovegood** [HammerPDF/Scholar-PDF-Reader#31]
新版本显示grobid 不可用

![image](https://user-images.githubusercontent.com/50430853/141031544-d558c52e-3d49-4c68-b8f8-011cefbd7d8c.png)

**Comment by wongself** [comment]
经过初步排查，我们发现学术服务器的网络连接出现了一些问题。
我们会加紧修复。给您带来不便，我们深感歉意。

**Comment by wongself** [comment]
学术服务已恢复，修复了部分进程占用内存过大的问题。

**Comment by LumosLovegood** [comment]
哇，辛苦辛苦，多谢！

**Comment by wangzk** [comment]
今天又出现了“Grobid 不可用 部分功能可能无法使用”的提示，还请查看一下是否是网络连接问题~ @wongself

**Comment by BITLiuSH** [comment]
非常感谢您的反馈。
学术服务器的网络环境出现了波动，目前已经修复。
给您带来不便，我们深感歉意。
