### ISSUE TITLE
获取论文实体信息失败

### ISSUE THREAD

**Issue by wangzk** [HammerPDF/Scholar-PDF-Reader#32]
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/2674020/142832407-bc6fc12b-f9d2-443f-af38-f2c7a97f09c5.png">

来自IEEE的挺正常的[一篇论文](https://ieeexplore.ieee.org/document/9458810)，提示“获取论文实体信息失败”，导致无法解析。

**Comment by BITLiuSH** [comment]
非常感谢您的反馈。
此次是由于服务器网络波动问题，导致信息抽取服务掉线。
已经重启相关服务，并测试此篇文章可以正常解析和抽取信息。

**Comment by wangzk** [comment]
感谢！Hammer PDF非常好用~
