### ISSUE TITLE
设为默认阅读器后，双击文件无法打开

### ISSUE THREAD

**Issue by LexTran** [HammerPDF/Scholar-PDF-Reader#34]
感谢贵团队的优秀工作，这次新版体验中我发现了软件的一个小缺陷。

举个例子，我把HammerPDF设置为默认PDF浏览器以后，在没有打开此软件的情况下， 如果直接双击PDF文件，只能够打开HammerPDF软件，但是软件中不会加载我想打开的文件，我必须再次双击想要打开的文件才会在软件中加载出来，这样子使用起来是否不太方便？

此外，不知道贵团队是否有计划在未来引入文献管理功能？

期待贵团队的下一次更新！

**Comment by wongself** [comment]
我们已经完成了文献管理功能的初步架构设计。但由于临近年末，团队成员的可支配时间的不足，文献管理模块的开发可能需要较长的一段时间来完成。

关于双击文件无法正常工作的问题，我们仍在调查，预计下一版本修复。

感谢您的反馈，我们仍将继续完善这一产品。
