### ISSUE TITLE
翻译

### ISSUE THREAD

**Issue by LGAG** [HammerPDF/Scholar-PDF-Reader#35]
当存在单词跨行时，翻译有时候会将其视为两个单词，希望可以解决一下这个bug

**Comment by LGAG** [comment]
另外我不理解为什么会将"multi-word"翻译成多世界，希望可以解决一下

**Comment by wongself** [comment]
Hammer PDF 目前使用的翻译接口来自百度，我们会在下个版本中加入 Google 翻译，并让用户自行选择翻译工具。

**Comment by LGAG** [comment]
但是单词跨行时被处理为两个独立的单词，这个不应该是文本预处理的问题吗，这个应该和翻译接口无关吧

**Comment by wongself** [comment]
> 但是单词跨行时被处理为两个独立的单词，这个不应该是文本预处理的问题吗，这个应该和翻译接口无关吧

对于存在跨行的文本，程序会执行替换换行符`\n`为`[空格]`的预处理，可能没有考虑到连词符存在的情况，我们将在下个版本中改进这一处理。
