### ISSUE TITLE
文件大小限制，云端存储以及数据来源扩充

### ISSUE THREAD

**Issue by yousiki** [HammerPDF/Scholar-PDF-Reader#4]
被导师安利后刚刚试用了一下，有不少惊艳的小功能。但同时也遇到一些问题，不知道开发组之后会不会着手解决。

- 文件大小限制，很多文献 PDF 的大小都远大于 5M
- 云端存储，类似于  Zotero 和 Mendeley 等软件的同步机制
- 似乎目前 HammerPDF 只能从 Sci-Hub 来获取 PDF，后续是否会增加对 arXiv 等网站的支持

祝 HammerPDF 越做越好！

**Comment by wongself** [comment]
> 被导师安利后刚刚试用了一下，有不少惊艳的小功能。但同时也遇到一些问题，不知道开发组之后会不会着手解决。
> 
> * 文件大小限制，很多文献 PDF 的大小都远大于 5M
> * 云端存储，类似于  Zotero 和 Mendeley 等软件的同步机制
> * 似乎目前 HammerPDF 只能从 Sci-Hub 来获取 PDF，后续是否会增加对 arXiv 等网站的支持
> 
> 祝 HammerPDF 越做越好！

预计在本周晚些时间发布的小版本修复更新里，我们会上调桌面端的文件大小限制至现有标准之上。另外，网页端的文件大小限制已上调至 5MB。

Hammer PDF 内置的学术搜索引擎 Hammer Scholar 已经对 arXiv 等主流网站进行了收录工作，且每天都会更新内容到 Hammer Scholar 学术数据库。当然，我们也将持续收录更多数据库以满足更多需求。

关于云端存储功能，现阶段的 Hammer PDF 没有计划去实现用户系统。但是，在稳定发布一些优化版本之后，我们将着手准备用户系统的设计与部署。

您可以在[此处](https://github.com/HammerPDF/Smart-Scientific-Reader/projects/1)查看本产品的项目工作安排。

**Comment by yousiki** [comment]
Thanks for your reply. Best wishes!
