### ISSUE TITLE
建议增加DeepL翻译

### ISSUE THREAD

**Issue by Mota-Link** [HammerPDF/Scholar-PDF-Reader#43]
百度和谷歌对于文献的翻译，语义相差太大了。DeepL翻译相对顺滑很多，能提高不少效率。

**Comment by BITLiuSH** [comment]
非常感谢您的反馈。
我们正在考虑是否增加DeepL翻译。

**Comment by wongself** [comment]
感谢您宝贵的建议，但受限于 DeepL 官方的业务范围，我们暂无法加入 DeepL Pro 的订阅计划。

**Comment by wongself** [comment]
我们已在网页版 (v1.2.0) 中添加了 DeepL 等多项翻译服务，目前仍在测试阶段，若有任何意见还请及时反馈。
