### ISSUE TITLE
希望加入pdf背景设置，可以设置为绿色的护眼模式

### ISSUE THREAD

**Issue by q77190858** [HammerPDF/Scholar-PDF-Reader#44]
希望可以改变背景纸张颜色，类似于金山pdf的护眼模式

**Comment by wongself** [comment]
感谢您的反馈，我们将调研 PDF.js 的渲染机制，以便分析该改进是否可行。

**Comment by wongself** [comment]
我们已在网页版 (v1.2.0) 中添加了黑暗主题，可前往设置页面调整。
该功能目前仍在测试阶段，若有任何意见还请及时反馈。
