### ISSUE TITLE
除了百度翻译以外其他翻译引擎都无法使用

### ISSUE THREAD

**Issue by sinbet2001** [HammerPDF/Scholar-PDF-Reader#45]
除了百度翻译可以正常使用外，选择其他翻译引擎后翻译任意文本都提示"获取翻译失败，请重试或更换翻译引擎"。

**Comment by wongself** [comment]
给您带来不便，我们深感歉意。
百度和谷歌翻译服务的实现方式是浏览器向官方端口请求数据。若无法访问其中一个，则需要检查网络是否正常。
其他翻译服务的实现是借助我们自行搭建的翻译引擎。此前服务器设备曾出现故障，设备重启后我们并未重新启动该引擎。
我们将在明日（28日）上午修复这一问题，感谢您的反馈。
