### ISSUE TITLE
是否考虑适配Mac M1呢?

### ISSUE THREAD

**Issue by aimuch** [HammerPDF/Scholar-PDF-Reader#47]
是否考虑适配Mac M1呢?

**Comment by wongself** [comment]
请问搭载 M1 芯片的 Mac 有什么兼容性问题么？

**Comment by wongself** [comment]
> 是否考虑适配Mac M1呢?

请问搭载 M1 芯片的 Mac 有什么兼容性问题么？

**Comment by wongself** [comment]
我们将在 v1.2.1 版本中发布适配了 ARM 版 Mac 的安装包。
