### ISSUE TITLE
后续会增加Linux版本吗？

### ISSUE THREAD

**Issue by Jamie-obj** [HammerPDF/Scholar-PDF-Reader#5]
目前政企正在推行国产化，一款好用易用的PDF软件很重要，不知是否会有Linux版本支持计划

**Comment by wongself** [comment]
本周晚些时间将发布 Linux 版 Hammer PDF。
另外，本问题已在[此处](https://github.com/HammerPDF/Smart-Scientific-Reader/issues/3)讨论过，故不再赘述。

**Comment by wongself** [comment]
Linux 版 Hammer PDF 已发布，详见[此处](https://github.com/HammerPDF/Smart-Scientific-Reader/releases/tag/v1.0.1)。
