### ISSUE TITLE
建议：提供翻译界面将中文放前面的设置

### ISSUE THREAD

**Issue by Jiang10086** [HammerPDF/Scholar-PDF-Reader#54]
![图片](https://user-images.githubusercontent.com/67213568/166441053-2993916d-c642-4382-a74b-af12876d293d.png)

如图，当选中内容较多时，看不到翻译后的内容，要翻一下才能看到，有些麻烦。除此之外，哪一点都比隔壁的知云强

**Comment by wongself** [comment]
感谢您的反馈，我们将在下个版本中对翻译结果界面进行调整，以提升译文的可见性。

**Comment by wongself** [comment]
现在，选中文字进行翻译时，过长的原文会被自动折叠，使得译文能在不移动滚轮的情况下可见。
该特性已更新至网页版。
