### ISSUE TITLE
几个pdf阅读器的基本功能没有做好

### ISSUE THREAD

**Issue by raintwoto** [HammerPDF/Scholar-PDF-Reader#67]
1.打开时不能记忆之前开关的目录或者学术窗口的开关，导致每次打开一个新文章都要关相应窗口
2.渲染体验不统一，有些引用能渲染出来，有些就不行，建议要不然都行，要不然都不行，设置一个百分比
3.pdf的转跳最好可以转跳回去

多谢

**Comment by raintwoto** [comment]
建议参考paperly，体验好很多

**Comment by wongself** [comment]
很抱歉给您带来使用上的不便，我们会继续改进使用逻辑。
对于你描述的问题，能否详细解释一下“转跳”的含义和“每次打开一个新文章都要关相应窗口”的意思？

**Comment by wongself** [comment]
> 建议参考paperly，体验好很多

确实有很多非常不错的功能，我们会尝试增加更多功能的。

**Comment by raintwoto** [comment]
跳转：pdf中的超链接点击后，发生跳转到另外一页，希望可以有啥方式回去
每次打开一个新文章都要关相应窗口：在没有关闭软件的情况下，在上个pdf中关闭了目录或者学术窗口，下个pdf打开的时候仍然打开目录或者学术窗口

**Comment by wongself** [comment]
我们将采纳您的建议，在下个版本中推出相应更新。
感谢您的反馈(^_^)v
