### ISSUE TITLE
我打开github经常连接不上

### ISSUE THREAD

**Issue by Marxinchina** [HammerPDF/Scholar-PDF-Reader#7]
我觉得是不是可以在国内弄一个下载地址而不是仅仅在github上，毕竟我下载中国的软件（可能是我的想法是错误的）还要翻墙不是什么好的体验

**Comment by wongself** [comment]
非常抱歉，由于网络问题而出现无法正常下载安装包的情况。我们后续将提供 Gitee 下载链接，届时会通知您。

**Comment by wongself** [comment]
我们已经在宣传页上提供了来自 Gitee.com 的下载链接。
