### ISSUE TITLE
Unable to use on Mac M1

### ISSUE THREAD

**Issue by mayank31398** [HammerPDF/Scholar-PDF-Reader#72]
<img width="242" alt="Screenshot 2023-02-17 at 10 04 34 PM" src="https://user-images.githubusercontent.com/32954280/219711132-c4bcb878-aefe-4a66-8547-c66b335a74ad.png">

**Comment by fightingxiaoxiao** [comment]
you can try `xattr -cr '/Applications/Hammer PDF.app'` in your terminal.

**Comment by mayank31398** [comment]
It worked thanks
