### ISSUE TITLE
咨询：请问日后的收费计划？

### ISSUE THREAD

**Issue by wslldsdhii** [HammerPDF/Scholar-PDF-Reader#8]
请问日和的收费计划。采用什么收费方式，可能的价格区间是什么。
如果可以一次买断，或者按年计费 100元/年 以内，我认为可以接受。
当然免费那就太好了，但是考虑到长期发展，收费是可以有的。或者对早期用户免费。

**Comment by wongself** [comment]
免费使用，暂无收费计划，请放心使用😊
