### ISSUE TITLE
Esc键失效

### ISSUE THREAD

**Issue by HMTTT** [HammerPDF/Scholar-PDF-Reader#9]
window环境，打开Hammer PDF后Esc键会失效，关掉就好了。
不知道是不是软件的问题，挺影响打字的。

**Comment by wongself** [comment]
我们经过初步检查发现，Hammer PDF 启动时会将 ESC 键进行全局热键注册，其功能变成「Hammer PDF 应用程序退出全屏状态」。
我们将在下个版本更新中修复这一错误。
